'use strict';

const path = require('path');

const LEVEL_PRIORITY = { inform: 1, warn: 2, ask: 3, block: 4 };

function classifyFile(filePath, graphQueries, config, project) {
  const h = config.hypothalamus || {};
  const ext = path.extname(filePath).toLowerCase();
  const basename = path.basename(filePath).toLowerCase();

  const matchedCategories = [];

  // database_files: final extension OR intermediate .db segment in name
  const dbFinalExts = ['.db', '.sqlite', '.sqlite3', '.db-wal', '.db-shm'];
  if (dbFinalExts.includes(ext) || /\.(db|sqlite|sqlite3)(\.|$)/.test(basename)) {
    matchedCategories.push('database_files');
  }

  // secret_files
  const secretFinalExts = ['.env', '.key', '.pem'];
  const secretNames = new Set([
    '.env', '.env.local', '.env.production', '.env.test',
    'credentials.json', 'secrets.json'
  ]);
  if (
    secretFinalExts.includes(ext) ||
    secretNames.has(basename) ||
    /^\.env(\.|$)/.test(basename) ||
    basename.endsWith('.secret')
  ) {
    matchedCategories.push('secret_files');
  }

  // config_files
  const configNames = new Set([
    'config.json', 'caddyfile', 'docker-compose.yml', 'docker-compose.yaml'
  ]);
  if (configNames.has(basename) || /\.config\.(js|ts|cjs|mjs)$/.test(basename)) {
    matchedCategories.push('config_files');
  }

  // Graph-based categories — require project + graphQueries
  let blastRadiusCount = 0;
  let generatorFile = null;
  const docReferences = [];

  if (project && graphQueries) {
    // high_blast_radius
    try {
      const blastResult = graphQueries.getBlastRadius(project, filePath);
      blastRadiusCount = blastResult.length;
      const threshold = h.blast_radius_threshold != null ? h.blast_radius_threshold : 5;
      if (blastRadiusCount >= threshold) {
        matchedCategories.push('high_blast_radius');
      }
    } catch { /* blast radius unavailable */ }

    // generated_files + documented_files via inbound edges
    try {
      const flow = graphQueries.getFileFlow(project, filePath);

      const generatorEdge = flow.inbound.find(
        e => e.type === 'writes_to' || e.type === 'generates'
      );
      if (generatorEdge) {
        matchedCategories.push('generated_files');
        try {
          const genNode = graphQueries.db
            .prepare('SELECT file FROM nodes WHERE id = ?')
            .get(generatorEdge.source_id);
          if (genNode) generatorFile = genNode.file;
        } catch {
          // Flow query failed — generator detection unavailable
        }
      }

      const docEdges = flow.inbound.filter(
        e => e.type === 'describes' || e.type === 'documents'
      );
      if (docEdges.length > 0) {
        matchedCategories.push('documented_files');
        for (const e of docEdges) {
          try {
            const n = graphQueries.db
              .prepare('SELECT file, line FROM nodes WHERE id = ?')
              .get(e.source_id);
            if (n) docReferences.push(`${n.file}:${n.line}`);
          } catch {
            // Node lookup failed — skip doc reference
          }
        }
      }
    } catch {
      // Flow graph unavailable — skip flow-based classification
    }
  }

  if (matchedCategories.length === 0) return null;

  // Determine highest alert level across all matched categories
  let highestLevel = 'inform';
  for (const cat of matchedCategories) {
    const level = h[cat] || 'inform';
    if ((LEVEL_PRIORITY[level] || 0) > (LEVEL_PRIORITY[highestLevel] || 0)) {
      highestLevel = level;
    }
  }

  return {
    categories: matchedCategories,
    level: highestLevel,
    details: { blastRadiusCount, generatorFile, docReferences }
  };
}

function formatAlert(classification) {
  if (!classification) return '';
  const { level, categories, details } = classification;

  const parts = [];
  if (categories.includes('database_files'))  parts.push('Database file');
  if (categories.includes('secret_files'))    parts.push('Secret/credential file');
  if (categories.includes('config_files'))    parts.push('Config file');
  if (categories.includes('high_blast_radius')) {
    parts.push(`High blast radius (${details.blastRadiusCount} dependents)`);
  }
  if (categories.includes('generated_files')) {
    parts.push(details.generatorFile
      ? `Generated by ${details.generatorFile}`
      : 'Generated file'
    );
  }
  if (categories.includes('documented_files')) {
    const refs = details.docReferences.length > 0
      ? ` (${details.docReferences.join(', ')})`
      : '';
    parts.push(`Referenced in docs${refs}`);
  }

  const context = parts.join('; ');

  switch (level) {
    case 'inform': return `[greymatter] ${context}`;
    case 'warn':   return `[greymatter] WARNING: ${context}`;
    case 'ask':    return `[greymatter] ${context}. Proceed?`;
    case 'block':  return `[greymatter] BLOCKED: ${context}. This action is not allowed.`;
    default:       return `[greymatter] ${context}`;
  }
}

module.exports = { classifyFile, formatAlert };
